version: '3.8'

services:
  dem-perm-web:
    image: ghcr.io/titouangragnic/dem-perm-client-ios:latest
    ports:
      - "8081:80"
    container_name: dem-perm-client-ios
    restart: unless-stopped
